


window.onscroll = function() {myFunction()};

var header = document.querySelector("#header");

//var sticky = header.offsetTop;





function myFunction()
{
   

    if(window.pageYOffset > sticky)
    {
        header.classList.add("sticky");
        console.log("Executed")

    }
    else
    {
        header.classList.remove("sticky")
    }



}


var hkData = [

    { id:1,
      image_url: "https://assets.ajio.com/medias/sys_master/root/h47/hb8/14876616851486/dnmx_black_mid-rise_fitted_jeans.jpg",
      tag: "DNMX",
      name: "Mid-Rise Fitted Jeans",
      price: "₹679",
      strikedoffprice: "₹799",
      discount : "(15% off)",
      offer: "Offer Price: ₹639",
    },
    { id:2,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20220301/TPXo/621d1530f997dd03e2f5346e/campus_grey_%26_orange_rollz_lace-up_running_shoes_with_contrast_heel_panel.jpg",
      tag: "CAMPUS",
      name: "Rollz Lace-up Running Shoes with Contrast Heel Panel",
      price: "₹1,199",
      strikedoffprice: "₹1,599",
      discount : "(25% off)",
      offer: "Offer Price: ₹839",
    },
    {id:3,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20200723/CFmP/5f19acf37cdb8c2207843537/crocs_navy_bayaband_slingback_clogs.jpg",
      tag: "CROCS",
      name: "Bayaband Slingback Clogs",
      price: "₹2,447",
      strikedoffprice: "₹3,495",
      discount : "(30% off)",
      offer: "Offer Price: ₹1,713",
    },
    {id:4,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20211013/uqO3/616622b1f997ddf8f1cd31ca/dillinger_green_colourblock_crew-_neck_t-shirt.jpg",
      tag: "DILLINGER",
      name: "Colourblock Crew-Neck T-shirt",
      price: "₹500",
      strikedoffprice: "₹1,249",
      discount : "(60% off)",
      offer: "Offer Price: ₹337",
    },
    {id:5,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20220125/NdPb/61ef13c0aeb2695cdd2bb6b8/performax_black_fastdry_active_panelled_track_pants.jpg",
      tag: "PERFORMAX",
      name: "Fastdry Active Pannelled Track Pants",
      price: "₹639",
      strikedoffprice: "₹799",
      discount : "(20% off)",
      offer: "Offer Price: ₹599",
    },
    {id:6,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20211231/oigB/61ce3c65aeb2695cddff3308/garcon_red_polo_t-shirt_with_spread_collar.jpg",
      tag: "Garcon",
      name: "Polo T-shirt with Spread Collar",
      price: "₹420",
      strikedoffprice: "₹1,199",
      discount : "(65% off)",
      offer: "Offer Price: ₹384",
    },
    {id:7,
      image_url: "https://assets.ajio.com/medias/sys_master/root/h79/h02/10267307016222/netplay_black_slim_fit_mid-rise_chinos.jpg",
      tag: "NETPLAY",
      name: "Slim Fit Mid-Rise Chinos",
      price: "₹799",
      strikedoffprice: "₹999",
      discount : "(20% off)",
      offer: "Offer Price: ₹749",
    },
    {id:8,
      image_url:"https://assets.ajio.com/medias/sys_master/root/20211104/01A4/6182d768aeb2690110b95a57/red_tape_navy_blue_textured_lace-up_sports_shoes.jpg"
      ,tag: "RED TAPE",
      name: "Textured Lace-Up Sports Shoes",
      price: "₹2,190",
      strikedoffprice: "₹7,299",
      discount : "(70% off)",
      offer: "Offer Price: ₹2,190",
    },
    {id:9,
      image_url:"https://assets.ajio.com/medias/sys_master/root/20211228/7icQ/61ca2db2aeb26901101f06cb/netplay_olive_green_jacquard-woven_slim_fit_polo_t-shirt.jpg",
      tag: "NETPLAY",
      name: "Jacquard-Woven Slim Fit Polo T-shirt",
      price: "₹639",
      strikedoffprice: "₹799",
      discount : "(20% off)",
      offer: "Offer Price: ₹599",
    },
    {id:10,
      image_url: "https://assets.ajio.com/medias/sys_master/root/h1d/h2e/15885260521502/dennislingo_premium_attire_blue_checked_slim_fit_shirt.jpg",
      tag: "DENNISLINGO PREMIUM ATTIRE",
      name: "Checked Slim Fit Shirt",
      price: "₹775",
      strikedoffprice: "₹2,499",
      discount : "(69% off)",
      offer: "Offer Price: ₹675",
    },
    {id:11,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20200723/6a8B/5f19adde7cdb8c2207844302/crocs_white_bayaband_clogs_with_slingback.jpg",
      tag: "CROCS",
      name: "Bayaband Clogs with Slingback",
      price: "₹2,447",
      strikedoffprice: "₹3,495",
      discount : "(30% off)",
      offer: "Offer Price: ₹1,713",
    },
    
    {id:12,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20220125/PQGG/61eef764f997dd662337fd2b/netplay_white_striped_button-down_t-shirt.jpg",
      tag: "NETPLAY",
      name: "Striped Button-Down T-shirt",
      price: "₹594",
      strikedoffprice: "₹699",
      discount : "(15% off)",
      offer: "Offer Price: ₹559",
    },
    {id:13,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20211009/Zkz6/61610103aeb2692b85bef82c/lee_cooper_blue_mid-rise_washed_slim_fit_jeans.jpg",
      tag: "Lee Cooper",
      name: "Mid-Rise Washed Slim Fit Jeans",
      price: "₹800",
      strikedoffprice: "₹1,599",
      discount : "(50% off)",
      offer: "Offer Price: ₹800",
    },
    {id:14,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20211019/Hn3u/616dc911aeb269011099ea26/campus_white_cassidy_lace-up_sneakers.jpg",
      tag: "Campus",
      name: "Cassidy Lace-Up Sneakers",
      price: "₹1,279",
      strikedoffprice: "₹1,599",
      discount : "(20% off)",
      offer: "Offer Price: ₹1,199",
    },
    {id:15,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20220212/o26y/6206bd3bf997dd03e2ccbd75/levis_blue_washed_slim_fit_jeans.jpg",
      tag: "Levis",
      name: "Washed Slim Fit Jeans",
      price: "₹1,559",
      strikedoffprice: "₹2,599",
      discount : "(40% off)",
      offer: "Offer Price: ₹1,325",
    },
    {id:16,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20210917/UdOX/6143d291aeb269a2689520c4/brooks_brothers_blue_striped_slim_fit_polo_t-shirt.jpg",
      tag: "BROOKS BROTHERS",
      name: "Striped Slim Fit Polo T-shirt",
      price: "₹5,500",
      strikedoffprice: "₹10,000",
      discount : "(45% off)",
      offer: "Offer Price: ₹4,400",
    },
    {id:17,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20211228/2WN1/61ca2003f997ddf8f1637a00/netplay_grey_slim_fit_flat-front_trousers.jpg",
      tag: "NETPLAY",
      name: "Slim Fit Flat-Front Trousers",
      price: "₹849",
      strikedoffprice: "₹999",
      discount : "(15% off)",
      offer: "Offer Price: ₹799",
    },
    {id:18,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20211013/NiBc/6166262baeb26901108e7692/puma__poly_cotton_cap_ind.jpg",
      tag: "Puma",
      name: "Poly Cotton Cap IND",
      price: "₹450",
      strikedoffprice: "₹899",
      discount : "(50% off)",
      offer: "Offer Price: ₹351",
    },
    {id:19,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20210724/NHOm/60fb3cd6f997ddb312375f4d/brooks_brothers_blue_checked_non-iron_stretch_regent_sport_shirt.jpg",
      tag: "BROOKS BROTHERS",
      name: "Checked Non-Iron Stretch Regent Sport Shirt",
      price: "₹5,200",
      strikedoffprice: "₹10,000",
      discount : "(48% off)",
      
    },
    {id:20,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20210403/dboC/6068dc56aeb269a9e33a5431/dennislingo_premium_attire_green_slim_fit_shirt_with_checked_detail.jpg",
      tag: "DENNISLINGO PREMIUM ATTIRE",
      name: "Slim Fit Shirt with Checked Detail",
      price: "₹775",
      strikedoffprice: "₹2,499",
      discount : "(69% off)",
      offer: "Offer Price: ₹675",
    },
    {id:21,
      image_url: "https://assets.ajio.com/medias/sys_master/root/hbf/h70/10295143923742/performax_blue_fastdry_active_essential_shorts.jpg",
      tag: "PERFORMAX",
      name: "Fastdry Active Essential Shorts",
      price: "₹299",
      strikedoffprice: "₹499",
      discount : "(40% off)",
      offer: "Offer Price: ₹200",
    },
    {id:22,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20211013/duCz/61662fe3aeb26901108f0774/dennislingo_premium_attire_pink_full_sleeves_slim_fit_classic_shirt.jpg",
      tag: "DNMX",
      name: "DENNISLINGO PREMIUM ATTIRE",
      price: "₹666",
      strikedoffprice: "₹1,849",
      discount : "(64% off)",
      offer: "Offer Price: ₹499",
    },
    {id:23,
      image_url: "https://assets.ajio.com/medias/sys_master/root/hc4/h66/10247899349022/dnmx_green_polo_t-shirt_with_signature_branding.jpg",
      tag: "DNMX",
      name: "Polo T-shirt with Signature Branding",
      price: "₹399",
      strikedoffprice: "₹499",
      discount : "(20% off)",
      offer: "Offer Price: ₹374",
    },
    {id:24,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20210413/HvAA/607491dfaeb269a9e38cd366/brooks_brothers_blue_floral_print_poplin_slim_fit_shirt.jpg",
      tag: "BROOKS BROTHERS",
      name: "Floral Print Poplin Slim Fit Shirt",
      price: "₹4,000",
      strikedoffprice: "₹8,000",
      discount : "(50% off)",
      offer: "Offer Price: ₹3,520",
    },
    {id:25,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20220205/mZqT/61fd75acaeb26921af8a8546/crocs_grey_bayaband_slip-on_clogs.jpg",
      tag: "CROCS",
      name: "Bayaband Slip-On Clogs",
      price: "₹2,447",
      strikedoffprice: "₹3,495",
      discount : "(30% off)",
      offer: "Offer Price: ₹1,713",
    },
    {id:26,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20220222/g1YT/621406c1f997dd03e2e03dcb/teamspirit_grey_trackpants_with_ribbed_drawstring_waist.jpg",
      tag: "Teamspirit",
      name: "Trackpants with Ribbed Drawstring Waist",
      price: "₹899",
      strikedoffprice: "₹999",
      discount : "(10% off)",
      offer: "Offer Price: ₹849",
    },
    {id:27,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20211104/TpUt/6182d5f6aeb2690110b953e9/red_tape_black_textured_lace-up_sports_shoes.jpg",
      tag: "RED TYPE",
      name: "Textured Lace-Up Sports Shoes",
      price: "₹2,190",
      strikedoffprice: "₹7,299",
      discount : "(70% off)",
      offer: "Offer Price: ₹2,190",
    },
    {id:28,
      image_url: "https://assets.ajio.com/medias/sys_master/root/hb3/hb4/15590223740958/teamspirit_maroon_heathered_polo_t-shirt.jpg",
      tag: "Teamspirit",
      name: "Heathered Polo T-shirt",
      price: "₹503",
      strikedoffprice: "₹599",
      discount : "(16% off)",
      offer: "Offer Price: ₹449",
    },
    {id:29,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20210526/NZQg/60ad7afbf997ddb312a9668a/campus_grey_panelled__slip-on_sports_shoes.jpg",
      tag: "Campus",
      name: "Panelled Slip-On Sports Shoes",
      price: "₹1,619",
      strikedoffprice: "₹1,799",
      discount : "(10% off)",
      offer: "Offer Price: ₹1,529",
    },
    {id:30,
      image_url:"https://assets.ajio.com/medias/sys_master/root/hf8/hae/14876749791262/dnmx_blue_lightly_washed_fitted_jeans.jpg",
      tag: "DNMX",
      name: "Lightly Washed Fitted Jeans",
      price: "₹679",
      strikedoffprice: "₹799",
      discount : "(15% off)",
      offer: "Offer Price: ₹639",
    },
    {id:31,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20210709/LI7n/60e79a30f997ddb312226e0d/campus_sutra_green_ombre-dyed_henley_t-shirt.jpg",
      tag: "Campus Sutra",
      name: "Ombre-Dyed Henley T-shirt",
      price: "₹476",
      strikedoffprice: "₹899",
      discount : "(47% off)",
      offer: "Offer Price: ₹441",
    },
    {id:32,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20210728/I1Im/61005afff997ddb3123c043b/john_players_jeans_black_washed_skinny_fit_jeans_with_whiskers.jpg",
      tag: "JOHN PLAYERS JEANS",
      name: "Washed Skinny Fit Jeans with Whiskers",
      price: "₹899",
      strikedoffprice: "₹999",
      discount : "(10% off)",
      offer: "Offer Price: ₹849",
    },
    {id:33,
      image_url: "https://assets.ajio.com/medias/sys_master/root/h5c/h2d/13003351883806/netplay_purple_cotton_shirt_with_patch_pocket.jpg",
      tag: "NETPLAY",
      name: "Cotton Shirt with Patch Pocket",
      price: "₹719",
      strikedoffprice: "₹899",
      discount : "(20% off)",
      offer: "Offer Price: ₹674",
    },
    {id:34,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20210420/R70k/607ecc5baeb269a9e3972075/dennislingo_premium_attire_green_full_sleeves_slim_fit_shirt.jpg",
      tag: "DENNINSLINGO PREMIUM ATTIRE",
      name: "Full Sleeves Slim Fit Shirt",
      price: "₹666",
      strikedoffprice: "₹1,849",
      discount : "(64% off)",
      offer: "Offer Price: ₹499",
    },
    {id:35,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20220216/pOV4/620bfa1bf997dd03e2d1ea22/dnmx_grey_mid-rise_washed_cropped_skinny_jeans.jpg",
      tag: "DNMX",
      name: "Mid-Rise Washed Cropped Skinny Jeans",
      price: "₹1,529",
      strikedoffprice: "₹1,444",
      discount : "(10% off)",
      offer: "Offer Price: ₹1,444",
    },
    {id:36,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20211013/WoWu/616627bdaeb26901108e8ea8/levis_assorted_pack_of_3_printed_boxers.jpg",
      tag: "LEVIS",
      name: "Pack of 3 Printed Boxers",
      price: "₹900",
      strikedoffprice: "₹1,799",
      discount : "(50% off)",
      offer: "Offer Price: ₹765",
    },
    {id:37,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20211027/MhKm/6179465cf997ddf8f1ecbbef/lee_cooper_blue_lightly_washed_slim_fit_jeans.jpg",
      tag: "Lee Cooper",
      name: "Lightly Washed Slim Fit Jeans",
      price: "₹934",
      strikedoffprice: "₹1,699",
      discount : "(45% off)",
      offer: "Offer Price: ₹394",
    },
    {id:38,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20210403/jgUz/6068af177cdb8c1f147a292c/the_bear_house_maroon_slim_fit_checked_shirt.jpg",
      tag: "THE BEAR HOUSE",
      name: "Slim Fit Checked Shirt",
      price: "₹1,123",
      strikedoffprice: "₹2,499",
      discount : "(55% off)",
      offer: "Offer Price: ₹1,098",
    },
    {id:39,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20220125/gnDj/61eefbe6aeb2695cdd2adfc4/performax_blue_fastdry_active_essential_shorts.jpg",
      tag: "PERFORMAX",
      name: "Fastdry Active Essential Shorts",
      price: "₹349",
      strikedoffprice: "₹499",
      discount : "(30% off)",
      offer: "Offer Price: ₹274",
    },
    {id:40,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20211013/dEHC/61663056f997ddf8f1ce0e18/campus_black_north_plus_lace-up_running_sports_shoes.jpg",
      tag: "Campus",
      name: "North Plus Lace-Up Running Sports Shoes",
      price: "₹1,444",
      strikedoffprice: "₹1,699",
      discount : "(15% off)",
      offer: "Offer Price: ₹1,444",
    },
    {id:41,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20220106/wMvi/61d70752f997dd662312edec/u.s._polo_assn._black_mid-rise_5-pocket_slim_jeans.jpg",
      tag: "U.S. Polo Assn.",
      name: "Mid-Rise 5-Pocket Slim Jeans",
      price: "₹1,359",
      strikedoffprice: "₹1,999",
      discount : "(32% off)",
      offer: "Offer Price: ₹1,155",
    },
    {id:31,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20210709/LI7n/60e79a30f997ddb312226e0d/campus_sutra_green_ombre-dyed_henley_t-shirt.jpg",
      tag: "Campus Sutra",
      name: "Ombre-Dyed Henley T-shirt",
      price: "₹476",
      strikedoffprice: "₹899",
      discount : "(47% off)",
      offer: "Offer Price: ₹441",
    },
    {id:31,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20210709/LI7n/60e79a30f997ddb312226e0d/campus_sutra_green_ombre-dyed_henley_t-shirt.jpg",
      tag: "Campus Sutra",
      name: "Ombre-Dyed Henley T-shirt",
      price: "₹476",
      strikedoffprice: "₹899",
      discount : "(47% off)",
      offer: "Offer Price: ₹441",
    },
    {id:31,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20210709/LI7n/60e79a30f997ddb312226e0d/campus_sutra_green_ombre-dyed_henley_t-shirt.jpg",
      tag: "Campus Sutra",
      name: "Ombre-Dyed Henley T-shirt",
      price: "₹476",
      strikedoffprice: "₹899",
      discount : "(47% off)",
      offer: "Offer Price: ₹441",
    },
    {id:31,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20210709/LI7n/60e79a30f997ddb312226e0d/campus_sutra_green_ombre-dyed_henley_t-shirt.jpg",
      tag: "Campus Sutra",
      name: "Ombre-Dyed Henley T-shirt",
      price: "₹476",
      strikedoffprice: "₹899",
      discount : "(47% off)",
      offer: "Offer Price: ₹441",
    },
    {id:31,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20210709/LI7n/60e79a30f997ddb312226e0d/campus_sutra_green_ombre-dyed_henley_t-shirt.jpg",
      tag: "Campus Sutra",
      name: "Ombre-Dyed Henley T-shirt",
      price: "₹476",
      strikedoffprice: "₹899",
      discount : "(47% off)",
      offer: "Offer Price: ₹441",
    },
    {id:31,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20210709/LI7n/60e79a30f997ddb312226e0d/campus_sutra_green_ombre-dyed_henley_t-shirt.jpg",
      tag: "Campus Sutra",
      name: "Ombre-Dyed Henley T-shirt",
      price: "₹476",
      strikedoffprice: "₹899",
      discount : "(47% off)",
      offer: "Offer Price: ₹441",
    },

    ];

hkData.map(function (elem) {
    var box = document.createElement("div");
  
    var img = document.createElement("img");
    img.src = elem.image_url;
    
    var tag = document.createElement("h2")
    tag.textContent=elem.tag;
    tag.style.color="#b29a76";
    var name = document.createElement("p");
    name.textContent = elem.name;

    var price = document.createElement("p");
    price.innerText = elem.price;
    price.style.fontWeight="bold";
     
     var sPrice = document.createElement("s");
     sPrice.innerText = elem.strikedoffprice;
     

    var offer = document.createElement("p");
    offer.innerText = elem.offer;

      var discount = document.createElement("p");
      discount.innerText = elem.discount;
      discount.style.color="#b29a76"
      


    box.append(img, tag, name, price,sPrice,discount, offer);
    document.querySelector("#datains").append(box)
   // document.querySelector("#datains").append(box);
  });
  