


window.onscroll = function() {myFunction()};

var header = document.querySelector("#header");

//var sticky = header.offsetTop;





function myFunction()
{
   

    if(window.pageYOffset > sticky)
    {
        header.classList.add("sticky");
        console.log("Executed")

    }
    else
    {
        header.classList.remove("sticky")
    }



}


var hkData = [

    { id:1,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20220218/DlZ0/620fa5d9f997dd03e2dbac50/indie_picks_multicolour_handblock_print_mull_cotton_door_curtain.jpg",
      tag: "DNMX",
      name: "Mid-Rise Fitted Jeans",
      price: "₹679",
      strikedoffprice: "₹799",
      discount : "(15% off)",
      offer: "Offer Price: ₹639",
    },
    { id:2,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20220301/TPXo/621d1530f997dd03e2f5346e/campus_grey_%26_orange_rollz_lace-up_running_shoes_with_contrast_heel_panel.jpg",
      tag: "CAMPUS",
      name: "Rollz Lace-up Running Shoes with Contrast Heel Panel",
      price: "₹1,199",
      strikedoffprice: "₹1,599",
      discount : "(25% off)",
      offer: "Offer Price: ₹839",
    },
    {id:3,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20200723/CFmP/5f19acf37cdb8c2207843537/crocs_navy_bayaband_slingback_clogs.jpg",
      tag: "CROCS",
      name: "Bayaband Slingback Clogs",
      price: "₹2,447",
      strikedoffprice: "₹3,495",
      discount : "(30% off)",
      offer: "Offer Price: ₹1,713",
    },
    {id:4,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20211013/uqO3/616622b1f997ddf8f1cd31ca/dillinger_green_colourblock_crew-_neck_t-shirt.jpg",
      tag: "DILLINGER",
      name: "Colourblock Crew-Neck T-shirt",
      price: "₹500",
      strikedoffprice: "₹1,249",
      discount : "(60% off)",
      offer: "Offer Price: ₹337",
    },
    {id:5,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20220125/NdPb/61ef13c0aeb2695cdd2bb6b8/performax_black_fastdry_active_panelled_track_pants.jpg",
      tag: "PERFORMAX",
      name: "Fastdry Active Pannelled Track Pants",
      price: "₹639",
      strikedoffprice: "₹799",
      discount : "(20% off)",
      offer: "Offer Price: ₹599",
    },
    {id:6,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20211231/oigB/61ce3c65aeb2695cddff3308/garcon_red_polo_t-shirt_with_spread_collar.jpg",
      tag: "Garcon",
      name: "Polo T-shirt with Spread Collar",
      price: "₹420",
      strikedoffprice: "₹1,199",
      discount : "(65% off)",
      offer: "Offer Price: ₹384",
    },
    {id:7,
      image_url: "https://assets.ajio.com/medias/sys_master/root/h79/h02/10267307016222/netplay_black_slim_fit_mid-rise_chinos.jpg",
      tag: "NETPLAY",
      name: "Slim Fit Mid-Rise Chinos",
      price: "₹799",
      strikedoffprice: "₹999",
      discount : "(20% off)",
      offer: "Offer Price: ₹749",
    },
    {id:8,
      image_url:"https://assets.ajio.com/medias/sys_master/root/20211104/01A4/6182d768aeb2690110b95a57/red_tape_navy_blue_textured_lace-up_sports_shoes.jpg"
      ,tag: "RED TAPE",
      name: "Textured Lace-Up Sports Shoes",
      price: "₹2,190",
      strikedoffprice: "₹7,299",
      discount : "(70% off)",
      offer: "Offer Price: ₹2,190",
    },
    {id:9,
      image_url:"https://assets.ajio.com/medias/sys_master/root/20211228/7icQ/61ca2db2aeb26901101f06cb/netplay_olive_green_jacquard-woven_slim_fit_polo_t-shirt.jpg",
      tag: "NETPLAY",
      name: "Jacquard-Woven Slim Fit Polo T-shirt",
      price: "₹639",
      strikedoffprice: "₹799",
      discount : "(20% off)",
      offer: "Offer Price: ₹599",
    },
    {id:10,
      image_url: "https://assets.ajio.com/medias/sys_master/root/h1d/h2e/15885260521502/dennislingo_premium_attire_blue_checked_slim_fit_shirt.jpg",
      tag: "DENNISLINGO PREMIUM ATTIRE",
      name: "Checked Slim Fit Shirt",
      price: "₹775",
      strikedoffprice: "₹2,499",
      discount : "(69% off)",
      offer: "Offer Price: ₹675",
    },
    {id:11,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20200723/6a8B/5f19adde7cdb8c2207844302/crocs_white_bayaband_clogs_with_slingback.jpg",
      tag: "CROCS",
      name: "Bayaband Clogs with Slingback",
      price: "₹2,447",
      strikedoffprice: "₹3,495",
      discount : "(30% off)",
      offer: "Offer Price: ₹1,713",
    },
    
    {id:12,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20220125/PQGG/61eef764f997dd662337fd2b/netplay_white_striped_button-down_t-shirt.jpg",
      tag: "NETPLAY",
      name: "Striped Button-Down T-shirt",
      price: "₹594",
      strikedoffprice: "₹699",
      discount : "(15% off)",
      offer: "Offer Price: ₹559",
    },
    {id:13,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20211009/Zkz6/61610103aeb2692b85bef82c/lee_cooper_blue_mid-rise_washed_slim_fit_jeans.jpg",
      tag: "Lee Cooper",
      name: "Mid-Rise Washed Slim Fit Jeans",
      price: "₹800",
      strikedoffprice: "₹1,599",
      discount : "(50% off)",
      offer: "Offer Price: ₹800",
    },
    {id:14,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20211019/Hn3u/616dc911aeb269011099ea26/campus_white_cassidy_lace-up_sneakers.jpg",
      tag: "Campus",
      name: "Cassidy Lace-Up Sneakers",
      price: "₹1,279",
      strikedoffprice: "₹1,599",
      discount : "(20% off)",
      offer: "Offer Price: ₹1,199",
    },
    {id:15,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20220212/o26y/6206bd3bf997dd03e2ccbd75/levis_blue_washed_slim_fit_jeans.jpg",
      tag: "Levis",
      name: "Washed Slim Fit Jeans",
      price: "₹1,559",
      strikedoffprice: "₹2,599",
      discount : "(40% off)",
      offer: "Offer Price: ₹1,325",
    },
    {id:16,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20210917/UdOX/6143d291aeb269a2689520c4/brooks_brothers_blue_striped_slim_fit_polo_t-shirt.jpg",
      tag: "BROOKS BROTHERS",
      name: "Striped Slim Fit Polo T-shirt",
      price: "₹5,500",
      strikedoffprice: "₹10,000",
      discount : "(45% off)",
      offer: "Offer Price: ₹4,400",
    },
    {id:17,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20211228/2WN1/61ca2003f997ddf8f1637a00/netplay_grey_slim_fit_flat-front_trousers.jpg",
      tag: "NETPLAY",
      name: "Slim Fit Flat-Front Trousers",
      price: "₹849",
      strikedoffprice: "₹999",
      discount : "(15% off)",
      offer: "Offer Price: ₹799",
    },
    {id:18,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20211013/NiBc/6166262baeb26901108e7692/puma__poly_cotton_cap_ind.jpg",
      tag: "Puma",
      name: "Poly Cotton Cap IND",
      price: "₹450",
      strikedoffprice: "₹899",
      discount : "(50% off)",
      offer: "Offer Price: ₹351",
    },
    {id:19,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20210724/NHOm/60fb3cd6f997ddb312375f4d/brooks_brothers_blue_checked_non-iron_stretch_regent_sport_shirt.jpg",
      tag: "BROOKS BROTHERS",
      name: "Checked Non-Iron Stretch Regent Sport Shirt",
      price: "₹5,200",
      strikedoffprice: "₹10,000",
      discount : "(48% off)",
      
    },
    {id:20,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20210403/dboC/6068dc56aeb269a9e33a5431/dennislingo_premium_attire_green_slim_fit_shirt_with_checked_detail.jpg",
      tag: "DENNISLINGO PREMIUM ATTIRE",
      name: "Slim Fit Shirt with Checked Detail",
      price: "₹775",
      strikedoffprice: "₹2,499",
      discount : "(69% off)",
      offer: "Offer Price: ₹675",
    },
    {id:21,
      image_url: "https://assets.ajio.com/medias/sys_master/root/hbf/h70/10295143923742/performax_blue_fastdry_active_essential_shorts.jpg",
      tag: "PERFORMAX",
      name: "Fastdry Active Essential Shorts",
      price: "₹299",
      strikedoffprice: "₹499",
      discount : "(40% off)",
      offer: "Offer Price: ₹200",
    },
    {id:22,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20211013/duCz/61662fe3aeb26901108f0774/dennislingo_premium_attire_pink_full_sleeves_slim_fit_classic_shirt.jpg",
      tag: "DNMX",
      name: "DENNISLINGO PREMIUM ATTIRE",
      price: "₹666",
      strikedoffprice: "₹1,849",
      discount : "(64% off)",
      offer: "Offer Price: ₹499",
    },
    {id:23,
      image_url: "https://assets.ajio.com/medias/sys_master/root/hc4/h66/10247899349022/dnmx_green_polo_t-shirt_with_signature_branding.jpg",
      tag: "DNMX",
      name: "Polo T-shirt with Signature Branding",
      price: "₹399",
      strikedoffprice: "₹499",
      discount : "(20% off)",
      offer: "Offer Price: ₹374",
    },
    {id:24,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20210413/HvAA/607491dfaeb269a9e38cd366/brooks_brothers_blue_floral_print_poplin_slim_fit_shirt.jpg",
      tag: "BROOKS BROTHERS",
      name: "Floral Print Poplin Slim Fit Shirt",
      price: "₹4,000",
      strikedoffprice: "₹8,000",
      discount : "(50% off)",
      offer: "Offer Price: ₹3,520",
    },
    {id:25,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20220205/mZqT/61fd75acaeb26921af8a8546/crocs_grey_bayaband_slip-on_clogs.jpg",
      tag: "CROCS",
      name: "Bayaband Slip-On Clogs",
      price: "₹2,447",
      strikedoffprice: "₹3,495",
      discount : "(30% off)",
      offer: "Offer Price: ₹1,713",
    },
    {id:26,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20220222/g1YT/621406c1f997dd03e2e03dcb/teamspirit_grey_trackpants_with_ribbed_drawstring_waist.jpg",
      tag: "Teamspirit",
      name: "Trackpants with Ribbed Drawstring Waist",
      price: "₹899",
      strikedoffprice: "₹999",
      discount : "(10% off)",
      offer: "Offer Price: ₹849",
    },
    {id:27,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20211104/TpUt/6182d5f6aeb2690110b953e9/red_tape_black_textured_lace-up_sports_shoes.jpg",
      tag: "RED TYPE",
      name: "Textured Lace-Up Sports Shoes",
      price: "₹2,190",
      strikedoffprice: "₹7,299",
      discount : "(70% off)",
      offer: "Offer Price: ₹2,190",
    },
    {id:28,
      image_url: "https://assets.ajio.com/medias/sys_master/root/hb3/hb4/15590223740958/teamspirit_maroon_heathered_polo_t-shirt.jpg",
      tag: "Teamspirit",
      name: "Heathered Polo T-shirt",
      price: "₹503",
      strikedoffprice: "₹599",
      discount : "(16% off)",
      offer: "Offer Price: ₹449",
    },
    {id:29,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20210526/NZQg/60ad7afbf997ddb312a9668a/campus_grey_panelled__slip-on_sports_shoes.jpg",
      tag: "Campus",
      name: "Panelled Slip-On Sports Shoes",
      price: "₹1,619",
      strikedoffprice: "₹1,799",
      discount : "(10% off)",
      offer: "Offer Price: ₹1,529",
    },
    {id:30,
      image_url:"https://assets.ajio.com/medias/sys_master/root/hf8/hae/14876749791262/dnmx_blue_lightly_washed_fitted_jeans.jpg",
      tag: "DNMX",
      name: "Lightly Washed Fitted Jeans",
      price: "₹679",
      strikedoffprice: "₹799",
      discount : "(15% off)",
      offer: "Offer Price: ₹639",
    },
    {id:31,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20210709/LI7n/60e79a30f997ddb312226e0d/campus_sutra_green_ombre-dyed_henley_t-shirt.jpg",
      tag: "Campus Sutra",
      name: "Ombre-Dyed Henley T-shirt",
      price: "₹476",
      strikedoffprice: "₹899",
      discount : "(47% off)",
      offer: "Offer Price: ₹441",
    },
    {id:32,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20210728/I1Im/61005afff997ddb3123c043b/john_players_jeans_black_washed_skinny_fit_jeans_with_whiskers.jpg",
      tag: "JOHN PLAYERS JEANS",
      name: "Washed Skinny Fit Jeans with Whiskers",
      price: "₹899",
      strikedoffprice: "₹999",
      discount : "(10% off)",
      offer: "Offer Price: ₹849",
    },
    {id:33,
      image_url: "https://assets.ajio.com/medias/sys_master/root/h5c/h2d/13003351883806/netplay_purple_cotton_shirt_with_patch_pocket.jpg",
      tag: "NETPLAY",
      name: "Cotton Shirt with Patch Pocket",
      price: "₹719",
      strikedoffprice: "₹899",
      discount : "(20% off)",
      offer: "Offer Price: ₹674",
    },
    {id:34,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20210420/R70k/607ecc5baeb269a9e3972075/dennislingo_premium_attire_green_full_sleeves_slim_fit_shirt.jpg",
      tag: "DENNINSLINGO PREMIUM ATTIRE",
      name: "Full Sleeves Slim Fit Shirt",
      price: "₹666",
      strikedoffprice: "₹1,849",
      discount : "(64% off)",
      offer: "Offer Price: ₹499",
    },
    {id:35,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20220216/pOV4/620bfa1bf997dd03e2d1ea22/dnmx_grey_mid-rise_washed_cropped_skinny_jeans.jpg",
      tag: "DNMX",
      name: "Mid-Rise Washed Cropped Skinny Jeans",
      price: "₹1,529",
      strikedoffprice: "₹1,444",
      discount : "(10% off)",
      offer: "Offer Price: ₹1,444",
    },
    {id:36,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20211013/WoWu/616627bdaeb26901108e8ea8/levis_assorted_pack_of_3_printed_boxers.jpg",
      tag: "LEVIS",
      name: "Pack of 3 Printed Boxers",
      price: "₹900",
      strikedoffprice: "₹1,799",
      discount : "(50% off)",
      offer: "Offer Price: ₹765",
    },
    {id:37,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20211027/MhKm/6179465cf997ddf8f1ecbbef/lee_cooper_blue_lightly_washed_slim_fit_jeans.jpg",
      tag: "Lee Cooper",
      name: "Lightly Washed Slim Fit Jeans",
      price: "₹934",
      strikedoffprice: "₹1,699",
      discount : "(45% off)",
      offer: "Offer Price: ₹394",
    },
    {id:38,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20210403/jgUz/6068af177cdb8c1f147a292c/the_bear_house_maroon_slim_fit_checked_shirt.jpg",
      tag: "THE BEAR HOUSE",
      name: "Slim Fit Checked Shirt",
      price: "₹1,123",
      strikedoffprice: "₹2,499",
      discount : "(55% off)",
      offer: "Offer Price: ₹1,098",
    },
    {id:39,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20220125/gnDj/61eefbe6aeb2695cdd2adfc4/performax_blue_fastdry_active_essential_shorts.jpg",
      tag: "PERFORMAX",
      name: "Fastdry Active Essential Shorts",
      price: "₹349",
      strikedoffprice: "₹499",
      discount : "(30% off)",
      offer: "Offer Price: ₹274",
    },
    {id:40,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20211013/dEHC/61663056f997ddf8f1ce0e18/campus_black_north_plus_lace-up_running_sports_shoes.jpg",
      tag: "Campus",
      name: "North Plus Lace-Up Running Sports Shoes",
      price: "₹1,444",
      strikedoffprice: "₹1,699",
      discount : "(15% off)",
      offer: "Offer Price: ₹1,444",
    },
    {id:41,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20220106/wMvi/61d70752f997dd662312edec/u.s._polo_assn._black_mid-rise_5-pocket_slim_jeans.jpg",
      tag: "U.S. Polo Assn.",
      name: "Mid-Rise 5-Pocket Slim Jeans",
      price: "₹1,359",
      strikedoffprice: "₹1,999",
      discount : "(32% off)",
      offer: "Offer Price: ₹1,155",
    },
    {id:42,
      image_url: "https://assets.ajio.com/medias/sys_master/root/20220120/qiRq/61e98217aeb2695cdd2244f1/performax_blue_heathered_crew-neck_t-shirt.jpg",
      tag: "PERFORMAX",
      name: "Heathered Crew-Neck T-shirt",
      price: "₹359",
      strikedoffprice: "₹599",
      discount : "(40% off)",
      offer: "Offer Price: ₹240",
    },
   

    ];

hkData.map(function (elem) {
    var box = document.createElement("div");
  
    var img = document.createElement("img");
    img.style.width="300px"
    
    img.src = elem.image_url;
    
    var tag = document.createElement("h2")
    tag.textContent=elem.tag;
    tag.style.color="#b29a76";
    var name = document.createElement("p");
    name.textContent = elem.name;

    var price = document.createElement("p");
    price.innerText = elem.price;
    price.style.fontWeight="bold";
     
     var sPrice = document.createElement("s");
     sPrice.innerText = elem.strikedoffprice;
     

    var offer = document.createElement("p");
    offer.innerText = elem.offer;

      var discount = document.createElement("p");
      discount.innerText = elem.discount;
      discount.style.color="#b29a76"
      


    box.append(img, tag, name, price,sPrice,discount, offer);
    document.querySelector("#datains").append(box)
  
  });
  

  // home and kitchen data

//   var HnKData = [

//     { id:1,
//       image_url: "https://assets.ajio.com/medias/sys_master/root/20211109/8lR5/618aa783f997ddf8f1ff477a/home_centre_beige_printed_stoneware_small_coffee_mug.jpg",
//       tag: "Home Centre",
//       name: "Printed Stoneware Small Coffee Mug",
//       price: "₹297",
//       strikedoffprice: "₹349",
//       discount : "(15% off)",
//       offer: "Offer Price: ₹297",
//     },
//     { id:2,
//       image_url: "https://assets.ajio.com/medias/sys_master/root/20211021/bSo7/617149b2f997ddf8f1df4b6a/good_homes_brown_room_darkening_dual_panel__window_curtain_set_of_2.jpg",
//       tag: "Good Homes",
//       name: "Room Darkening Dual Panel Window Curtain Set of 2",
//       price: "₹480",
//       strikedoffprice: "₹1,199",
//       discount : "(60% off)",
//       offer: "Offer Price: ₹324",
//     },
//     {id:3,
//       image_url: "https://assets.ajio.com/medias/sys_master/root/20211128/I4Z7/61a3306ef997ddf8f120d296/shades_of_life_blue_set_of_2_embroidered_cushion_cover_16%27%27_x_16%27%27.jpg",
//       tag: "Shades Of Life",
//       name: "Set of 2 Embroidered Cushion Cover 16x16 ",
//       price: "₹1,140",
//       strikedoffprice: "₹1,200",
//       discount : "(5% off)",
//       offer: "Offer Price: ₹936",
//     },
//     {id:4,
//       image_url: "https://assets.ajio.com/medias/sys_master/root/20211012/J9Tz/6165bf8df997dd3ed46cddcd/portico_multicoloured_happiness_is_collection_super_king_size_bedsheet_with_2_pillow_covers.jpg",
//       tag: "PORTICO",
//       name: "Happiness Is Collection Super King Size Bedsheet with 2 Pillow Covers",
//       price: "₹2,337",
//       strikedoffprice: "₹2,749",
//       discount : "(15% off)",
      
//     },
//     {id:5,
//       image_url: "https://assets.ajio.com/medias/sys_master/root/20210827/Sqx9/61292ca2aeb269a26880ca58/portico_multicoloured_melange_printed_single_reversible_comforter.jpg",
//       tag: "PORTICO",
//       name: "Melange Printed Single Reversible Comforter",
//       price: "₹1,799",
//       strikedoffprice: "₹2,999",
//       discount : "(40% off)",
      
//     },
//     {id:6,
//       image_url: "https://assets.ajio.com/medias/sys_master/root/20220315/dYkk/622fa8c4aeb26921afd82fca/rosarahome_grey_%26_clear_pack_of_4_printed_door_curtains.jpg",
//       tag: "Rosarahome",
//       name: "Pack of 4 Printed Door Curtains",
//       price: "₹4,479",
//       strikedoffprice: "₹6,399",
//       discount : "(30% off)",
//       offer: "Offer Price: ₹3.494",
//     },
//     {id:7,
//       image_url: "https://assets.ajio.com/medias/sys_master/root/20220114/OdlB/61e08d45f997dd6623208bb9/decorealm_pink_300_tc_poly_satin_king_bedsheet_with_pillow_covers.jpg",
//       tag: "DECOREALM",
//       name: "300 TC Poly Satin King Bedsheet with Pillow Covers",
//       price: "₹2,246",
//       strikedoffprice: "₹4,990",
//       discount : "(55% off)",
//       offer: "Offer Price: ₹1,437",
//     },
//     {id:8,
//       image_url:"https://assets.ajio.com/medias/sys_master/root/20210506/45E8/6093ff41aeb269a9e3b4f1cf/houzzcode_grey_printed_blackout_door_curtain.jpg"
//       ,tag: "Houzzcode",
//       name: "Printed Blackout Door Curtain",
//       price: "₹1,259",
//       strikedoffprice: "₹2,099",
//       discount : "(40% off)",
//       offer: "Offer Price: ₹806",
//     },
//     {id:9,
//       image_url:"https://assets.ajio.com/medias/sys_master/root/20211116/qeuw/6192b34daeb2690110c55778/good_homes_navy_heart_printed_bed_sheet_%26_pillow_covers.jpg",
//       tag: "Good Homes",
//       name: "Heart Printed Bed Sheet & Pillow Covers",
//       price: "₹540",
//       strikedoffprice: "₹1,199",
//       discount : "(55% off)",
//       offer: "Offer Price: ₹346",
//     },
//     {id:10,
//       image_url: "https://assets.ajio.com/medias/sys_master/root/20220215/I3w4/620bc610aeb26921af99f884/portico_aqua_cotton_queen-size_comforter.jpg",
//       tag: "PORTICO",
//       name: "Cotton Queen-Size Comforter",
//       price: "₹2,000",
//       strikedoffprice: "₹3,999",
//       discount : "(50% off)",
      
//     },
//     {id:11,
//       image_url: "https://assets.ajio.com/medias/sys_master/root/20211024/nW9T/617578a5aeb2690110a6f567/home_centre_white_textured_foam_pillow.jpg",
//       tag: "Home Centre",
//       name: "Textured Foam Pillow",
//       price: "₹3,824",
//       strikedoffprice: "₹4,499",
//       discount : "(15% off)",
//       offer: "Offer Price: ₹3,824",
//     },
    
//     {id:12,
//       image_url: "https://assets.ajio.com/medias/sys_master/root/20220207/DDGy/6201425aaeb26921af8d092e/indie_picks_white_hand_embroidered_cotton_cushion_cover_16%22_x_16%22.jpg",
//       tag: "Indie Picks",
//       name: "hand Embroidered Cotton Cushion Cover",
//       price: "₹479",
//       strikedoffprice: "₹799",
//       discount : "(40% off)",
//       offer: "Offer Price: ₹345",
//     },
//     {id:13,
//       image_url: "https://assets.ajio.com/medias/sys_master/root/20211108/8cNS/61890b17f997ddf8f1fb2a2a/home_centre_pink_artificial_lotus_bud.jpg",
//       tag: "Home Centre",
//       name: "Artificial Lotus Bud",
//       price: "₹254",
//       strikedoffprice: "₹299",
//       discount : "(15% off)",
//       offer: "Offer Price: ₹254",
//     },
//     {id:14,
//       image_url: "https://assets.ajio.com/medias/sys_master/root/20211013/L0mj/616630edf997ddf8f1ce175f/portico_multicoloured_happiness_is_collection_super_king_size_bedsheet_with_2_pillow_covers.jpg",
//       tag: "PORTICO",
//       name: "Happiness Is Collection Super King Size Bedsheet",
//       price: "₹2,749",
      
//     },
//     {id:15,
//       image_url: "https://assets.ajio.com/medias/sys_master/root/20220121/BKaS/61ea6e30aeb2695cdd259aa0/home_sizzler_brown_set_of_2_leaf_panel_eyelet_door_curtains.jpg",
//       tag: "Home Sizzler",
//       name: "Set of 2 Leaf Panel Eyelet Door Curtains",
//       price: "₹499",
//       strikedoffprice: "₹799",
//       discount : "(40% off)",
//       offer: "Offer Price: ₹374",
//     },
//     {id:16,
//       image_url: "https://assets.ajio.com/medias/sys_master/root/20210825/Io01/612558347cdb8cb82404f23a/portico_new_york_multicoloured_120_gsm_floral_print_king_size_reversible_comforter.jpg",
//       tag: "PORTICO NEW YORK",
//       name: "120 GSM FLoral Print King Size Reversible",
//       price: "₹2,519",
//       strikedoffprice: "₹4,199",
//       discount : "(40% off)",
//       offer: "Offer Price: ₹2,519",
//     },
//     {id:17,
//       image_url: "https://assets.ajio.com/medias/sys_master/root/20211101/vzRH/617fe509aeb2690110b53929/home_centre_gold_wall_mounted_t-light_holder.jpg",
//       tag: "Home Centre",
//       name: "Wall Mounted T-light Holder",
//       price: "₹1,869",
//       strikedoffprice: "₹2,199",
//       discount : "(15% off)",
//       offer: "Offer Price: ₹1,869",
//     },
//     {id:18,
//       image_url: "https://assets.ajio.com/medias/sys_master/root/20211129/cyRJ/61a50eb7f997ddf8f1243471/home_centre_green_courage_beaded_glass_placemat.jpg",
//       tag: "Home Centre",
//       name: "Courage Beaded Glass Placemat",
//       price: "₹594",
//       strikedoffprice: "₹699",
//       discount : "(15% off)",
//       offer: "Offer Price: ₹594",
//     },
//     {id:19,
//       image_url: "https://assets.ajio.com/medias/sys_master/root/20220302/zhO6/621f3242f997dd03e2fc768c/marks_%26_spencer_grey_egyptian_cotton_230_tc_flat_bedsheet.jpg",
//       tag: "Marks & Spencer",
//       name: "Egyptian Cotton 230 TC Flat Bedsheet",
//       price: "₹2,499",
      
      
//     },
//     {id:20,
//       image_url: "https://assets.ajio.com/medias/sys_master/root/20210921/Z9dC/6148fcdcaeb269a2689a41ba/portico_multicoloured_shalimaar_printed_reversible_king-size_comforter.jpg",
//       tag: "PORTICO",
//       name: "SHalimaar Printed Reversible King-Size Comforter",
//       price: "₹2,519",
//       strikedoffprice: "₹2,199",
//       discount : "(40% off)",
      
//     },
//     {id:21,
//       image_url: "https://assets.ajio.com/medias/sys_master/root/20200912/uajF/5f5bcfc37cdb8c766299ad6b/muji_brown_cotton_pile_thick_face_towel.jpg",
//       tag: "MUJI",
//       name: "Cotton Pile Thick Face Towel",
//       price: "₹595",
//       strikedoffprice: "₹1,190",
//       discount : "(50% off)",
//       offer: "Offer Price: ₹488",
//     },
//     {id:22,
//       image_url:"https://assets.ajio.com/medias/sys_master/root/20210506/dn60/6093facaf997ddb3129341c9/lavichitra_beige_pack_of_3_braided_jute_placemats.jpg" 
//      , tag: "Lavichitra",
//       name: "Pack of 3 Braided Jute Placemats",
//       price: "₹474",
//       strikedoffprice: "₹499",
//       discount : "(5% off)",
//       offer: "Offer Price: ₹389",
//     },
//     {id:23,
//       image_url: "https://assets.ajio.com/medias/sys_master/root/20211016/Wphq/6169ecfef997ddf8f1d511e6/raymond_home_white_floral_printed_double_bedsheet.jpg",
//       tag: "Raymond Home",
//       name: "Floral Printed Double Bedsheet",
//       price: "₹934",
//       strikedoffprice: "₹1,699",
//       discount : "(45% off)",
//       offer: "Offer Price: ₹598",
//     },
//     {id:24,
//       image_url: "https://assets.ajio.com/medias/sys_master/root/20210622/kYPR/60d1b7fbaeb269a9e3058749/swayam_beige_set_of_2_eyelets_door_curtain.jpg",
//       tag: "Swayam",
//       name: "Set of 2 Eyelets Door Curtain",
//       price: "₹2,469",
//       strikedoffprice: "₹3,799",
//       discount : "(35% off)",
//       offer: "Offer Price: ₹1,580",
//     },
//     {id:25,
//       image_url: "https://assets.ajio.com/medias/sys_master/root/20211129/xaCP/61a5011daeb2690110e13995/home_centre_green_courage_green_glass_beaded_table_runner_-_89_x_37_cm.jpg",
//       tag: "Home Center",
//       name: "Courage Green Glass Beaded Table Runner",
//       price: "₹1,359",
//       strikedoffprice: "₹1,599",
//       discount : "(15% off)",
//       offer: "Offer Price: ₹1,359",
//     },
//     {id:26,
//       image_url: "https://assets.ajio.com/medias/sys_master/root/20200912/tO7f/5f5bc2d5aeb269ef8ebd941b/muji_navy_cotton_thick_face_towel.jpg",
//       tag: "MUJI",
//       name: "Cotton Thick Face Towel",
//       price: "595",
//       strikedoffprice: "₹1,190",
//       discount : "(50% off)",
//       offer: "Offer Price: ₹488",
//     },
//     {id:27,
//       image_url: "https://assets.ajio.com/medias/sys_master/root/20211022/47qZ/6171cbbbf997ddf8f1e120e7/home_centre_red_helina_printed_rectangular_platter.jpg",
//       tag: "Home Centre",
//       name: "Helina Printed Rectangular Platter",
//       price: "₹849",
//       strikedoffprice: "₹999",
//       discount : "(15% off)",
//       offer: "Offer Price: ₹849",
//     },
//     {id:28,
//       image_url: "https://assets.ajio.com/medias/sys_master/root/20211203/emnR/61aa6c73f997ddf8f1368b4b/portico_beige_300_tc_printed_king_size_duvet_cover.jpg",
//       tag: "PORTICO",
//       name: "300 TC Printed King Size Duvet Cover",
//       price: "₹1,600",
//       strikedoffprice: "₹3,199",
//       discount : "(50% off)",
      
//     },
//     {id:29,
//       image_url: "https://assets.ajio.com/medias/sys_master/root/20220315/uHtp/622f99c6f997dd03e212135f/bichauna_maroon_104_tc_indian_print_cotton_single_bedsheet_with_1_pillow_cover.jpg",
//       tag: "BICHAUNA",
//       name: "104 TC Indian Print Cotton Single Bedsheet with 1 Pillow Cover",
//       price: "₹459",
     
//     },
//     {id:30,
//       image_url:"https://assets.ajio.com/medias/sys_master/root/20211216/ypnF/61bb5481aeb26901100f380a/portico_brown_printed_super_king_bedsheet_with_2_pillow_covers.jpg",
//       tag: "PORTICO",
//       name: "Printed King Bedsheet with 2 Pillow Covers",
//       price: "₹1,600",
//       strikedoffprice: "₹3,199",
//       discount : "(50% off)",
     
//     },
//     {id:31,
//       image_url: "https://assets.ajio.com/medias/sys_master/root/20211006/nxGp/615dafd2aeb2692b85b1b890/home_centre_blue_floral_printed__king-size_bedsheet__.jpg",
//       tag: "Home Centre",
//       name: "Floral Printed King-Size Bedsheet",
//       price: "₹1,104",
//       strikedoffprice: "₹1,299",
//       discount : "(15% off)",
//       offer: "Offer Price: ₹1,104",
//     },
//     {id:32,
//       image_url: "https://assets.ajio.com/medias/sys_master/root/20210825/N1Ky/61255bf17cdb8cb82404fca2/portico_new_york_blue_%26_white_120_gsm_checked_reversible_double_size_comforter.jpg",
//       tag: "PORTICO NEW YORK",
//       name: "120 GSM Checked Reversible Double Size Comforter",
//       price: "₹1,919",
//       strikedoffprice: "₹3,199",
//       discount : "(40% off)",
//       offer: "Offer Price: ₹1,919",
//     },
//     {id:33,
//       image_url: "https://assets.ajio.com/medias/sys_master/root/20220315/kXOp/622fb823f997dd03e21393bb/bichauna_white_120_tc_indian_print_cotton_double_bedsheet_with_2_pillow_covers.jpg",
//       tag: "BICHAUNA",
//       name: "120 TC Indian Print Cotton Double Bedsheet with 2 Pillow Covers",
//       price: "₹799",
      
//     },
//     {id:34,
//       image_url: "https://assets.ajio.com/medias/sys_master/root/20210827/qIAs/61290d37aeb269a26880976c/portico_multicoloured_mix_don%27t_match_double_reversible_dohar.jpg",
//       tag: "PORTICO",
//       name: "Mix Don't Match Double Reversible Dohar",
//       price: "₹2,719",
//       strikedoffprice: "₹3,199",
//       discount : "(15% off)",
      
//     },
//     {id:35,
//       image_url: "https://assets.ajio.com/medias/sys_master/root/20211128/P9Ww/61a321e1f997ddf8f11fc9b0/sashaa_world_multicoloured_hand_tufted_cotton_cushion.jpg",
//       tag: "SASHAA WORLD",
//       name: "Hand Tufted Cotton Cushion",
//       price: "₹950",
//       offer: "Offer Price: ₹855",
//     },
//     {id:36,
//       image_url: "https://assets.ajio.com/medias/sys_master/root/20220307/5g8r/6226219ef997dd03e204930d/bella_casa_red_150gsm_floral_print_reversible_blanket_.jpg",
//       tag: "BELLA CASA",
//       name: "150GSM Floral Print Reversible Blanket",
//       price: "₹900",
//       strikedoffprice: "₹1,999",
//       discount : "(55% off)",
//       offer: "Offer Price: ₹576",
//     },
//     {id:37,
//       image_url: "https://assets.ajio.com/medias/sys_master/root/20220127/5nuZ/61f2df50aeb2695cdd3352e4/habere_india_beige_hand_woven_jute_circular_shape_carpet_.jpg",
//       tag: "Habere India",
//       name: "Hand Woven Jute Circular Shape Carpet",
//       price: "₹1,950",
//       strikedoffprice: "₹6,499",
//       discount : "(70% off)",
//       offer: "Offer Price: ₹1,755",
//     },
//     {id:38,
//       image_url: "https://assets.ajio.com/medias/sys_master/root/20220221/wcOy/62138838aeb26921afa57369/portico_new_york_white_striped_cotton_bath_towel.jpg",
//       tag: "PORTICO NEW YORK",
//       name: "Striped Cotton Bath Towel",
//       price: "₹4,25",
//       strikedoffprice: "₹849",
//       discount : "(50% off)",
//       offer: "Offer Price: ₹425",
//     },
//     {id:39,
//       image_url: "https://assets.ajio.com/medias/sys_master/root/20220125/2ZnX/61efce77aeb2695cdd2e6e40/ddecor_live_beautiful_multi_leaf_printed_double_bedsheet.jpg",
//       tag: "Decor Live Beautiful",
//       name: "Leaf Printed Double Bedsheet",
//       price: "₹1,399",
//       offer: "Offer Price: ₹1,091",
//     },
//     {id:40,
//       image_url: "https://assets.ajio.com/medias/sys_master/root/20220301/ICh2/621e0e81aeb26921afbe8268/bella_casa_purple_printed_reversible_double_dohar.jpg",
//       tag: "BELLA CASA",
//       name: "Printed Reversible Double Dohar",
//       price: "₹900",
//       strikedoffprice: "₹1,999",
//       discount : "(55% off)",
//       offer: "Offer Price: ₹576",
//     },
//     {id:41,
//       image_url: "https://assets.ajio.com/medias/sys_master/root/20211108/v8vy/61890b34aeb2690110ba6cc1/home_centre_gold_embellished_metal_%26_glass_diya__holder.jpg",
//       tag: "Home Centre",
//       name: "Embellished Metal & Glass Diya Holder",
//       price: "₹467",
//       strikedoffprice: "₹549",
//       discount : "(15% off)",
//       offer: "Offer Price: ₹467",
//     },
//     {id:42,
//       image_url: "https://assets.ajio.com/medias/sys_master/root/20210920/OHrV/61484919f997ddce89cd3d52/urban_dream_pink_printed_mercerised_cotton_double_bed_sheet_with_2_pillow_cover.jpg",
//       tag: "URBAN DREAM",
//       name: "Printer Mercerised Cotton Double Bed Sheet With 2 Pillow Cover",
//       price: "₹1,699",
//       strikedoffprice: "₹2,499",
//       discount : "(32% off)",
//       offer: "Offer Price: ₹1,087",
//     },
   

//     ];

// HnKData.map(function (elem) {
//     var box = document.createElement("div");
  
//     var img = document.createElement("img");
//     img.src = elem.image_url;
    
//     var tag = document.createElement("h2")
//     tag.textContent=elem.tag;
//     tag.style.color="#b29a76";
//     var name = document.createElement("p");
//     name.textContent = elem.name;

//     var price = document.createElement("p");
//     price.innerText = elem.price;
//     price.style.fontWeight="bold";
     
//      var sPrice = document.createElement("s");
//      sPrice.innerText = elem.strikedoffprice;
     

//     var offer = document.createElement("p");
//     offer.innerText = elem.offer;

//       var discount = document.createElement("p");
//       discount.innerText = elem.discount;
//       discount.style.color="#b29a76"
      
//     box.append(img, tag, name, price,sPrice,discount, offer);
  

//     document.querySelector("#container").append(box);
//   });
// </script>
